### ISSUE TITLE
Exporter Deployment not using correct secret key

### ISSUE THREAD

**Issue by anthonyvg9** [castai/egressd#65]
For example here:
```
        {{- if or .Values.castai.apiKey .Values.castai.apiKeySecretRef }}
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              {{- if .Values.castai.apiKey }}
              name: "{{- include "egressd.fullname" . }}"
              key: API_KEY
```
it should be:
```
              name: "{{- include "egressd.fullname" . }}"
              key: .Values.castai.apiKey
```
not `key: API_KEY`
