### ISSUE TITLE
Headers are not propagated to Mimir endpoint

### ISSUE THREAD

**Issue by Hy3n4** [castai/egressd#98]
Hey,

we are trying to convince `egressd-exporter` to push metrics into our mimir cluster. So far we are unable to do that using custom headers. In this case, we are using `X-Scope-OrgID` to define the target tenant ID. All metrics coming in under anonymous (which is the default when `X-Scope-OrgID` is not defined in req).

Here is the content of the `values.yaml` file:

```
castai:
  apiKey: <redacted>
  apiURL: https://api.cast.ai
  clusterID: <redacted>
collector:
  serviceAccount:
    create: false
    name: egressd
exporter:
  serviceAccount:
    create: false
    name: egressd-exporter
  structuredConfig:
    sinks:
      mimir:
        prom_remote_write:
          headers:
            X-Scope-OrgID: tenant1
          url: http://<redacted>/api/v1/push
```
I think that all indentations are correct, yet there is still no tenantID in the request.

I tried to write the client using the `promwrite` package in Go and can confirm that it works correctly.

So far we used nginx proxy as a workaround where we're injecting the correct header.

May I ask for a pair of eyes on our config if there's something obvious that we're missing?
